NAME = bureaucrats
FLAGS = -Wall -Wextra -Werror -std=c++98
SRC = main.cpp Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp \
		PresidentialPardonForm.cpp



all :
	c++ $(FLAGS)  $(SRC) -o $(NAME)

fclean :
	rm -f $(NAME)
