NAME = materia 
FLAGS = -Wall -Wextra -Werror -std=c++98 -g -fsanitize=address
SRC = main.cpp AMateria.cpp Ice.cpp Cure.cpp Character.cpp MateriaSource.cpp 



all :
	c++ $(FLAGS)  $(SRC) -o $(NAME)

fclean :
	rm -f $(NAME)
